# Set a plain language title for the site.
title: JTD Demo

# Write a short description for the site. This is used for "meta description."
description: Experiment with Just the Docs for Methods

# Set the language for the site. Used for "html lang." Default is English.
lang: en

# Add Google Analytics if needed. Replace placeholder with site ID.
ga: UA-XXXXX-Y

# Avoid GitHub API authentication when building locally. (Not working)
github: [metadata]

# Add Just the Docs theme
# theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true